### ISSUE TITLE
[INFO] can work on DLP-RFID2 + MSP430F2370

### ISSUE THREAD

**Issue by et-ness** [gentilkiwi/st25tb_kiemul#1]
Hi, thank you for your project.

a few years ago I tried to create the same thing but I failed.
I have a DLP-RFID2 with integrated MSP430F2370 microcontroller, do you think your firmware can work anyway? 
Although I know it requires a bit of modification since the driverlibs are not there for the 430F2xx series.

**Comment by gentilkiwi** [comment]
Maybe, maybe not, I don't have this kit and it's not a very useful one in comparaison to Launchpad ones.

Their "simplified" schematic it not helpful to determine how it works internally
![image](https://github.com/user-attachments/assets/0cfac6ef-146f-4ba8-87d0-fb2aed48cf5a)
But it seems to use SPI, so - yes, I suppose you can make something around it by adding the correct driverlib to the project and with a lots of adjustments!

**Comment by et-ness** [comment]
Sure it use SPI, change only the microcontroller, 430F2370 instead of 430F5529.
driverlib don't support 430F2370 but I should already have some code developed to set the GPIO and SPI.
DLP-7970ABP use DLP-RFID2 (without microcontroller) + antenna on pcb + some leds.
