### ISSUE TITLE
[INFO] TRF7970A_init never invoked

### ISSUE THREAD

**Issue by et-ness** [gentilkiwi/st25tb_kiemul#2]
Is it normal which the function TRF7970A_init is never invoked?

**Comment by gentilkiwi** [comment]
Normal, I don't know, but I was testing if it was necessary (or not) when also calling: https://github.com/gentilkiwi/st25tb_kiemul/blob/main/st25tb/st25tb.c#L74 - it seems not, but just in case I keep it (kameleon still use it)
