### ISSUE TITLE
TRF7970A_clearIrqStatus don't clear IRQ

### ISSUE THREAD

**Issue by et-ness** [gentilkiwi/st25tb_kiemul#4]
I'm trying to make st25tb_kamaleon work on my DLP-RFID2 and I'm having problems with the IRQ, basically I always read 0x0 after receiving the interrupt.

So looking for a solution to the problem I noticed that TRF7970A_clearIrqStatus does not work correctly, from datasheet 6.10.5 
```
The dummy read is required in SPI mode because
the reader's IRQ status register needs an additional clock cycle to clear the register.
```

This should be the correct version that respects the datasheet:
```
uint8_t TRF7970A_getIrqStatus()
{
    uint8_t buf;
    TRF7970A_readCont(buf, TRF79X0_IRQ_STATUS_REG, 2);
    return buf[0];
}
.......
#define TRF7970A_clearIrqStatus()   TRF7970A_getIrqStatus()
```

However it doesn't solve my problems, but I think it is right to respect the datasheet, even if everything works fine.
The same problem also exists on st25tb_kameleon, I haven't checked the other microcontrollers.

**Comment by gentilkiwi** [comment]
The TRF stack is the same on others µC, as I share with them a lots of same code, and you're right: as I was with an approach on strict minimal implementation to keep some µs, if I can avoid to send one byte, I avoid it :')

This edge case is important when you read the IRQ and wait immediatly for another IRQ (eg. not the wanted one received) - I will take a look to try to add it and measure impacts (I don't think I will use readCont loop for a single dummy byte by eg.)

It did not solve your problems, but doest it - at least avoid the `0x00` data received ?

**Comment by et-ness** [comment]
> at least avoid the `0x00` data received ?

I explained badly, what I always read at 0x00 is the value of the register 0x0C IRQ_STATUS_REG, so it doesn't even read the RX buffer.
I don't understand how it is possible that an IRQ fires and no flags are set.

If I try this stupid code:

```
do {
    *pTRF7970A_irqStatus = TRF7970A_getIrqStatus();
while(*pTRF7970A_irqStatus==0);
```

I see 0x04 IRQ_STATUS_RF, most likely when the RF radio from the reader is turned off.
I'll check the conversion of the code, something has definitely missing, even if I haven't changed your part, precisely to avoid running into these strange problems.

**Comment by gentilkiwi** [comment]
The only place I saw IRQ firing without nothing is during RESET/SOFT INIT.

**Comment by gentilkiwi** [comment]
Just pushed some code to add the IRQ dummy read support - enabled by default.
Undef `TRF7970A_IRQ_USE_DUMMY_READ` in `main.h` to toggle between.
